apiVersion: v1
kind: Pod
metadata:
  name: request-wiki
  labels:
    app: request-wiki
spec:
  containers:
    - name: request-wiki
      image: hadyrashwan/request-wiki:0.0.3
      args:
        - "-http=0.0.0.0:3000"
        - "-health=0.0.0.0:81"
        - "-secret=secret"
      ports:
        - name: http
          containerPort: 300
        - name: health
          containerPort: 81
      resources:
        limits:
          cpu: 0.2
          memory: "300Mi"
