apiVersion: v1
kind: Service
metadata:
  labels:
    name: request-wiki
  name:  request-wiki
spec:
  selector:
    app: request-wiki
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 3000
  type: LoadBalancer
