apiVersion: v1
kind: Service
metadata:
  labels:
    name: request-wiki
  name:  request-wiki-service
spec:
  selector:
    app: request-wiki
  ports:
#  - name: app
  - port: 8000
    protocol: TCP
    nodePort: 30061
#  - name: external-connection
#    port: 80
#    protocol: TCP
  type: LoadBalancer
