apiVersion: v1
kind: Service
metadata:
  labels:
    name: request-wiki
  name:  request-wiki-service
spec:
  selector:
    app: request-wiki
  ports:
    - name: app
      port: 3000
      protocol: TCP
      targetPort: 8000
    - name: app
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
