apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: request-wiki-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: request-wiki
    spec:
      containers:
      - name: request-wiki
        image: hadyrashwan/request-wiki:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 80
